name: Install Nodejs Dependencies

description: installs dependancies

inputs:
  GithubToken:
    description: 'Auth token for the repos GHPR'
    required: false

runs:
  using: 'composite'

  steps:
    - name: Get pnpm cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      shell: bash

    - name: Cache node modules
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      uses: actions/cache@v3
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-${{ hashFiles('.tool-versions') }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ hashFiles('.tool-versions') }}-yarn-

    - name: yarn install
      shell: bash
      run: yarn install --immutable
